# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 09:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='name',
        ),
    ]
